name: Blue-Green Deploy

on:
  push:
    branches: [main]

env:
  REGION: europe-west1
  DOCKER_REGISTRY_HOST: europe-west1-docker.pkg.dev
  GC_PROJECT_ID: just-vent-235315
  IMAGE: revolut-hello/app
  GIT_HASH_IMAGE_VERSION_SHORT: 123123
  GOOGLE_APPLICATION_CREDENTIALS: ./google-cloud-credentials.json

jobs:
  build-and-deploy:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Install Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.5.7

    - name: Init necessary variables
      run: echo '${{ secrets.GCP_JSON_KEY }}' > $GOOGLE_APPLICATION_CREDENTIALS

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to GCR
      uses: docker/login-action@v3
      with:
        registry: ${{ env.DOCKER_REGISTRY_HOST }}
        username: _json_key
        password: ${{ secrets.GCP_JSON_KEY }}

    - name: Build and push
      uses: docker/build-push-action@v6 
      with:
        context: .
        push: true
        tags: ${{ env.DOCKER_REGISTRY_HOST }}/${{ env.GC_PROJECT_ID }}/${{ env.IMAGE }}:${{ env.GIT_HASH_IMAGE_VERSION_SHORT }}

    - name: Terraform init
      run: terraform init

    - name: Terraform apply
      run: terraform apply -auto-approve -no-color -lock=false -var "git_hash_image_version=${{ env.GIT_HASH_IMAGE_VERSION_SHORT }}"