name: Verify Application

on:
  pull_request:
    branches: [ main ]

jobs:
  verify:
    runs-on: ubuntu-22.04
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci

    - name: Run tests
      run: npm test
      
    # TODO:
    # add test coverage upload and puglishing of testing result into the pull request